/**
 * Bulk Image Upload — filename-to-offer matching. Pure and side-effect
 * free: given a filename and the set of offer_codes valid for this batch,
 * decides which offer (if any) and which slot (hero vs. gallery position)
 * it belongs to. No I/O, no upload, no database — BulkImageImportService
 * calls this once per file and acts on the result.
 *
 * Offer ID is the ONLY supported matching key — never merchant name, offer
 * title, or category. Those are free text an admin or ChatGPT export can
 * phrase inconsistently; offer_code is the one value guaranteed unique and
 * exact, generated by Pairley itself at Excel-import time.
 */

/** e.g. "OFF000123.jpg" -> code 123, slot 0. "OFF000123_2.PNG" -> code 123, slot 2. */
const FILENAME_PATTERN = /^OFF0*(\d+)(?:_(\d+))?\.(jpe?g|png|webp)$/i;

export const SUPPORTED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'webp'];

export type ImageMatchOutcome =
  | { kind: 'MATCHED'; code: number; slot: number }
  | { kind: 'INVALID_FILENAME' };

/**
 * Parses a filename into an offer code and slot. Slot 0 (no suffix, or
 * `_0`) is the hero image; `_1`, `_2`, ... are gallery images in that
 * order. Does not check whether the offer/slot actually exists — that
 * requires the batch's offer set and is the caller's job (see
 * matchImageToOffer below), kept separate so this stays a pure string ->
 * structure parse with nothing to mock in a test.
 */
export function parseImageFilename(fileName: string): ImageMatchOutcome {
  const match = FILENAME_PATTERN.exec(fileName.trim());
  if (!match) return { kind: 'INVALID_FILENAME' };
  const code = Number(match[1]);
  const slot = match[2] !== undefined ? Number(match[2]) : 0;
  if (!Number.isFinite(code) || code <= 0) return { kind: 'INVALID_FILENAME' };
  return { kind: 'MATCHED', code, slot };
}

export type ImageMappingDecision =
  | { status: 'MAPPED'; offerId: string; slot: number; code: number }
  | { status: 'MISSING_OFFER'; code: number; slot: number }
  | { status: 'DUPLICATE'; offerId: string; slot: number; code: number }
  | { status: 'INVALID_FILE' };

/**
 * The full per-file decision: parse the name, look up the code against
 * this batch's offers, and check the slot isn't already taken by an
 * earlier file in the same upload. `offerCodeToId` and `takenSlots` are
 * both scoped to one batch by the caller — a code from a DIFFERENT
 * batch's offers must never match here, otherwise one admin's upload could
 * silently paint another's offers.
 *
 * Every outcome except INVALID_FILE carries the parsed code/slot, even
 * when nothing matched — MISSING_OFFER and DUPLICATE both have a genuine
 * parse result, and reporting it back (rather than just the bare status)
 * is what lets the upload report tell an admin exactly which code a file
 * was trying to match, not just that it failed.
 */
export function decideImageMapping(
  fileName: string,
  offerCodeToId: ReadonlyMap<number, string>,
  takenSlots: ReadonlySet<string>, // keys are `${offerId}:${slot}`
): ImageMappingDecision {
  const parsed = parseImageFilename(fileName);
  if (parsed.kind === 'INVALID_FILENAME') return { status: 'INVALID_FILE' };

  const offerId = offerCodeToId.get(parsed.code);
  if (!offerId)
    return { status: 'MISSING_OFFER', code: parsed.code, slot: parsed.slot };

  const slotKey = `${offerId}:${parsed.slot}`;
  if (takenSlots.has(slotKey)) {
    return {
      status: 'DUPLICATE',
      offerId,
      slot: parsed.slot,
      code: parsed.code,
    };
  }

  return { status: 'MAPPED', offerId, slot: parsed.slot, code: parsed.code };
}
