import { BusinessStatus } from '@prisma/client';
import { renderPairleyCopy, Locale } from './pairleyCopyTemplates';
import { TemplateId, resolveTemplate } from './bannerTemplates';
import {
  computeCostSplit,
  buildUnlockSteps,
  buildWhyPairleyBullets,
  buildDealUrl,
  CostSplit,
  UnlockStep,
} from './costSplitBanner';
import { BannerBranding, resolveBranding } from './bannerBranding';

/**
 * Module 14 Phase 3B — everything about a Pairley banner that can be decided
 * without touching an image.
 *
 * Split from the renderer deliberately: escaping, truncation, price maths and
 * badge selection are where the real bugs live, and they're all testable as
 * plain functions. The sharp/SVG layer stays thin enough to be obviously
 * correct.
 *
 * Banners are *composed from a template*, never generated by an image model —
 * a banner is a layout with ~10 text fields (price, group size, discount,
 * business name), and image models render text unreliably. Composition gives
 * exact text, identical branding every time, no per-image cost, and instant
 * regeneration after an admin edit.
 */

export const BANNER_WIDTH = 1080;
export const BANNER_HEIGHT = 1080;

// Aligned with what the renderer can actually fit: the title gets two lines
// at 60px, the headline one line at 38px, the body four lines at 30px, all
// within a 952px content column. wrapLines() is still the authority — these
// just stop a wildly long string travelling that far.
const MAX_TITLE_CHARS = 50;
const MAX_HEADLINE_CHARS = 40;
const MAX_BUSINESS_CHARS = 34;
const MAX_BODY_CHARS = 190;
const MAX_LOCATION_CHARS = 30;

/**
 * Badge vocabulary. Note what is absent: an imported public offer is never
 * labelled "Pairley Exclusive". It is the merchant's own publicly advertised
 * offer, from a business that may not even have joined Pairley yet — calling
 * it exclusive would be a false claim to customers. `EXCLUSIVE` is reserved
 * for offers a merchant genuinely gave Pairley exclusively.
 */
export type BannerBadge =
  | 'VERIFIED'
  | 'CLAIMED'
  | 'CURATED'
  | 'DISCOVERED'
  | 'EXCLUSIVE'
  | null;

export const BADGE_LABELS: Record<Exclude<BannerBadge, null>, string> = {
  VERIFIED: 'Verified by Pairley',
  CLAIMED: 'Claimed Business',
  CURATED: 'Pairley Curated',
  DISCOVERED: 'Discovered on Pairley',
  EXCLUSIVE: 'Pairley Exclusive',
};

export interface BannerInput {
  title: string;
  /** Accepts a raw string: values arrive from request bodies. */
  offerType: string;
  originalPrice?: number | null;
  offerPrice?: number | null;
  requiredPeople?: number | null;
  category?: string | null;
  businessName?: string | null;
  businessStatus?: string | null;
  city?: string | null;
  mallName?: string | null;
  /** Whether the merchant has been reviewed and verified by Pairley. */
  merchantVerified?: boolean;
  /** True only for offers a merchant gave Pairley exclusively. */
  isPairleyExclusive?: boolean;
  /** Where the offer came from — MANUAL means merchant-created. */
  source?: string | null;
  heroImageUrl?: string | null;
  logoUrl?: string | null;
  locale?: Locale;
  /** Module 14 Phase 3C — which layout to compose. Defaults to 'A'. */
  templateId?: string | null;
  /** Needed only to build the Template F QR code — see costSplitBanner.ts. */
  offerId?: string | null;
  /** A genuine aggregate from the Rating table; never a fabricated figure. */
  businessRating?: { average: number; count: number } | null;
  /** Merchant's requested banner branding; honoured only when claimed. */
  brandingMode?: string | null;
  /** Merchant's brand colour; strictly validated before use. */
  brandColor?: string | null;
}

export interface BannerLayout {
  width: number;
  height: number;
  title: string;
  businessName: string;
  headline: string;
  body: string;
  location: string;
  categoryKey: string;
  offerTypeLabel: string;
  groupLabel: string | null;
  originalPriceLabel: string | null;
  offerPriceLabel: string;
  savingsLabel: string | null;
  discountLabel: string | null;
  badge: BannerBadge;
  badgeLabel: string | null;
  heroImageUrl: string | null;
  /** Merchant logos are withheld for unclaimed businesses — see decideLogo. */
  logoUrl: string | null;
  ctaLabel: string;
  templateId: TemplateId;
  /** Template F only — null for every other template, and null for F too
   *  when there's no honest split to show (see computeCostSplit). */
  costSplit: CostSplit | null;
  unlockSteps: UnlockStep[];
  whyBullets: string[];
  dealUrl: string | null;
  /** e.g. "4.6 (128 reviews)" — omitted entirely when the business has no
   *  real ratings yet, never shown as a fabricated placeholder. */
  businessRatingLabel: string | null;
  /** Resolved branding — always populated, always with validated colours. */
  branding: BannerBranding;
}

/** A-E share the square canvas; F is landscape to hold its richer content
 *  (cost box + steps + partner card side by side), matching the reference
 *  design's proportions rather than force-fitting it into a square. */
const TEMPLATE_DIMENSIONS: Record<
  TemplateId,
  { width: number; height: number }
> = {
  A: { width: 1080, height: 1080 },
  B: { width: 1080, height: 1080 },
  C: { width: 1080, height: 1080 },
  D: { width: 1080, height: 1080 },
  E: { width: 1080, height: 1080 },
  F: { width: 1200, height: 900 },
};

/**
 * Widest plausible advance per character, as a fraction of font size.
 *
 * SVG has no text measurement, and the rendering container may not have a
 * proportional font installed — `font-family="sans-serif"` then falls back
 * to a monospace face whose glyphs are markedly wider than a proportional
 * one. Sizing against the *widest* case means text can look a little loose
 * when a proportional font is present, but never runs off the canvas, which
 * is the failure that actually matters on a public marketing image.
 */
const CHAR_ADVANCE_RATIO = 0.62;

/** How many characters of `fontSize` fit within `availableWidth`. */
export function charsThatFit(availableWidth: number, fontSize: number): number {
  const advance = fontSize * CHAR_ADVANCE_RATIO;
  if (!Number.isFinite(advance) || advance <= 0) return 1;
  return Math.max(1, Math.floor(availableWidth / advance));
}

/**
 * Greedy word wrap into at most `maxLines`, ellipsising the last line when
 * the text doesn't fit. Returns lines already truncated to width — the
 * renderer draws them verbatim.
 */
export function wrapLines(
  text: string,
  charsPerLine: number,
  maxLines: number,
): string[] {
  const clean = String(text ?? '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!clean) return [];

  const words = clean.split(' ');
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length <= charsPerLine) {
      current = candidate;
      continue;
    }
    if (current) lines.push(current);
    // A single word longer than the line gets hard-split rather than
    // silently overflowing.
    if (word.length > charsPerLine) {
      let rest = word;
      while (rest.length > charsPerLine && lines.length < maxLines) {
        lines.push(rest.slice(0, charsPerLine));
        rest = rest.slice(charsPerLine);
      }
      current = rest;
    } else {
      current = word;
    }
    if (lines.length >= maxLines) break;
  }

  if (current && lines.length < maxLines) lines.push(current);

  if (lines.length > maxLines) lines.length = maxLines;

  // If anything was dropped, mark the final line so the cut is visible
  // rather than looking like the copy simply ended.
  const rendered = lines.join(' ');
  if (rendered.length < clean.length) {
    const last = lines[lines.length - 1] ?? '';
    lines[lines.length - 1] =
      last.length >= charsPerLine
        ? `${last.slice(0, Math.max(1, charsPerLine - 1))}…`
        : `${last}…`;
  }

  return lines;
}

/** XML-escape. Every string reaching the SVG layer must pass through this. */
export function escapeXml(value: string): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Collapses whitespace and truncates on a word boundary where possible. */
export function truncate(value: string, max: number): string {
  const clean = String(value ?? '')
    .replace(/\s+/g, ' ')
    .trim();
  if (clean.length <= max) return clean;

  const cut = clean.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(' ');
  // Only break on a word if that doesn't leave a stub.
  const body = lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut;
  return `${body.trimEnd()}…`;
}

/** Indian-format currency, e.g. 30000 -> "₹30,000". */
export function formatPrice(value: number): string {
  const rounded = Math.round(Number(value) || 0);
  return `₹${rounded.toLocaleString('en-IN')}`;
}

/**
 * Percentage off, or null when there is no genuine discount to claim.
 * Guards the cases that would otherwise print nonsense on a public banner:
 * a zero/absent original price, an offer price above the original, or a
 * discount that rounds to 0%.
 */
export function computeDiscountPercent(
  originalPrice?: number | null,
  offerPrice?: number | null,
): number | null {
  const original = Number(originalPrice);
  const offer = Number(offerPrice);
  if (!Number.isFinite(original) || !Number.isFinite(offer)) return null;
  if (original <= 0 || offer < 0) return null;
  if (offer >= original) return null;

  const percent = Math.round(((original - offer) / original) * 100);
  return percent > 0 ? percent : null;
}

/**
 * Badge priority. Verified beats claimed beats curated beats discovered.
 * An imported offer can never reach EXCLUSIVE — that flag is only honoured
 * for merchant-created (MANUAL) offers, so an admin cannot accidentally
 * publish a false exclusivity claim on a scraped listing.
 */
export function decideBadge(input: BannerInput): BannerBadge {
  const isImported = Boolean(input.source) && input.source !== 'MANUAL';

  if (input.merchantVerified) return 'VERIFIED';
  if (input.isPairleyExclusive && !isImported) return 'EXCLUSIVE';
  if (input.businessStatus === BusinessStatus.CLAIMED) return 'CLAIMED';
  if (isImported) return 'DISCOVERED';
  return 'CURATED';
}

/**
 * A merchant's logo is their trademark. Compositing it into a Pairley-branded
 * banner for a business that hasn't claimed its listing would imply an
 * endorsement that doesn't exist, so the logo is withheld until the merchant
 * claims and manages their own branding. The business name renders as text
 * instead, which carries the same information without the implication.
 */
export function decideLogo(input: BannerInput): string | null {
  if (input.businessStatus !== BusinessStatus.CLAIMED) return null;
  return input.logoUrl || null;
}

export function buildLocation(input: BannerInput): string {
  const parts = [input.mallName, input.city].filter((part): part is string =>
    Boolean(part && String(part).trim()),
  );
  return truncate(parts.join(', '), MAX_LOCATION_CHARS);
}

export function offerTypeLabel(offerType: string): string {
  return String(offerType || 'STANDARD')
    .split('_')
    .map((word) => word.charAt(0) + word.slice(1).toLowerCase())
    .join(' ');
}

/**
 * The one entry point: an offer plus its business becomes a fully-resolved,
 * escape-safe layout. The renderer does no decision-making of its own.
 */
export function buildBannerLayout(input: BannerInput): BannerLayout {
  const copy = renderPairleyCopy(input.offerType, {
    requiredPeople: input.requiredPeople,
    locale: input.locale,
  });

  const discount = computeDiscountPercent(
    input.originalPrice,
    input.offerPrice,
  );
  const original = Number(input.originalPrice);
  const offer = Number(input.offerPrice) || 0;
  const hasRealOriginal =
    Number.isFinite(original) && original > 0 && original > offer;
  const savings = hasRealOriginal ? original - offer : null;

  const badge = decideBadge(input);
  const requiredPeople = Number(input.requiredPeople) || 0;
  const templateId = resolveTemplate(input.templateId).id;

  const branding = resolveBranding({
    requestedMode: input.brandingMode,
    businessStatus: input.businessStatus,
    brandColor: input.brandColor,
    // decideLogo already applies the unclaimed-business rule to the URL
    // itself, so this is consistent by construction rather than by two
    // separate checks that could drift apart.
    hasLogo: Boolean(decideLogo(input)),
  });

  // Merchant branding trades Pairley's trust bullets for hero emphasis: the
  // taller photo and the full bullet list cannot both fit above the CTA bar
  // (verified by rendering — the overflow was real), and under Mode B the
  // merchant's own identity is what's meant to lead. Pairley branding keeps
  // the full list.
  const allBullets = buildWhyPairleyBullets(
    input.businessStatus,
    input.merchantVerified,
  );
  const whyBullets =
    branding.mode === 'MERCHANT' ? allBullets.slice(0, 2) : allBullets;
  const dimensions = TEMPLATE_DIMENSIONS[templateId];

  const rating = input.businessRating;
  const businessRatingLabel =
    rating && rating.count > 0
      ? escapeXml(
          `${rating.average.toFixed(1)} (${
            rating.count >= 1000
              ? `${(rating.count / 1000).toFixed(1)}K+`
              : rating.count
          } review${rating.count === 1 ? '' : 's'})`,
        )
      : null;

  return {
    width: dimensions.width,
    height: dimensions.height,
    title: escapeXml(truncate(input.title || 'Special Offer', MAX_TITLE_CHARS)),
    businessName: escapeXml(
      truncate(input.businessName || 'Local Business', MAX_BUSINESS_CHARS),
    ),
    headline: escapeXml(truncate(copy.headline, MAX_HEADLINE_CHARS)),
    body: escapeXml(truncate(copy.body, MAX_BODY_CHARS)),
    location: escapeXml(buildLocation(input)),
    categoryKey: String(input.category || 'shopping').toLowerCase(),
    offerTypeLabel: escapeXml(offerTypeLabel(input.offerType)),
    groupLabel:
      requiredPeople > 1 ? escapeXml(`${requiredPeople} people needed`) : null,
    originalPriceLabel: hasRealOriginal
      ? escapeXml(formatPrice(original))
      : null,
    offerPriceLabel: escapeXml(formatPrice(offer)),
    savingsLabel: savings ? escapeXml(`Save ${formatPrice(savings)}`) : null,
    discountLabel: discount ? escapeXml(`${discount}% OFF`) : null,
    badge,
    badgeLabel: badge ? escapeXml(BADGE_LABELS[badge]) : null,
    heroImageUrl: input.heroImageUrl || null,
    logoUrl: decideLogo(input),
    ctaLabel: 'Show Interest',
    templateId,
    costSplit: computeCostSplit(
      input.originalPrice,
      input.offerPrice,
      input.requiredPeople,
    ),
    unlockSteps: buildUnlockSteps(input.requiredPeople),
    whyBullets,
    dealUrl: buildDealUrl(input.offerId),
    businessRatingLabel,
    branding,
  };
}
