import sharp from 'sharp';
import { ImageAnalysisService } from './image-analysis.service';

const originalFetch = global.fetch;

// Real sharp against real generated bytes throughout — the whole point of
// this service is measurements sharp actually produces, so mocking sharp
// would test nothing. Only the network fetch (probe()) is mocked; buffer
// analysis (analyseBuffer()) runs unmocked in every test below.
async function pngBuffer(svg: string): Promise<Buffer> {
  return sharp(Buffer.from(svg)).png().toBuffer();
}

const RECT = (w: number, h: number, fill: string) =>
  `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg"><rect width="${w}" height="${h}" fill="${fill}"/></svg>`;

describe('ImageAnalysisService (Module 14 Phase 3C)', () => {
  let service: ImageAnalysisService;

  beforeEach(() => {
    service = new ImageAnalysisService();
    global.fetch = jest.fn();
  });

  afterAll(() => {
    global.fetch = originalFetch;
  });

  describe('analyseBuffer — dimensions and format', () => {
    it('reads real width, height, aspect ratio and format', async () => {
      const buffer = await pngBuffer(RECT(1600, 900, '#334455'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.ok).toBe(true);
      expect(probe.width).toBe(1600);
      expect(probe.height).toBe(900);
      expect(probe.aspectRatio).toBeCloseTo(1.778, 2);
      expect(probe.format).toBe('png');
      expect(probe.orientation).toBe('landscape');
    });

    it('classifies a portrait image', async () => {
      const buffer = await pngBuffer(RECT(900, 1600, '#334455'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.orientation).toBe('portrait');
    });

    it('classifies a square image', async () => {
      const buffer = await pngBuffer(RECT(1000, 1000, '#334455'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.orientation).toBe('square');
    });

    it('reports the actual buffer size', async () => {
      const buffer = await pngBuffer(RECT(400, 400, '#000000'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.fileSizeBytes).toBe(buffer.length);
    });
  });

  describe('analyseBuffer — brightness and contrast', () => {
    it('measures a dark image as low brightness', async () => {
      const buffer = await pngBuffer(RECT(400, 400, '#050505'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.brightness).toBeLessThan(0.1);
    });

    it('measures a bright image as high brightness', async () => {
      const buffer = await pngBuffer(RECT(400, 400, '#fafafa'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.brightness).toBeGreaterThan(0.9);
    });

    it('measures a flat single-colour image as near-zero contrast', async () => {
      const buffer = await pngBuffer(RECT(400, 400, '#556677'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.contrast).toBeLessThan(0.02);
    });

    it('measures a high-contrast (checkerboard) image as higher contrast than a flat one', async () => {
      const checker = `<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="400" height="400" fill="#000"/>
        <rect x="0" y="0" width="200" height="200" fill="#fff"/>
        <rect x="200" y="200" width="200" height="200" fill="#fff"/>
      </svg>`;
      const flatBuf = await pngBuffer(RECT(400, 400, '#556677'));
      const checkerBuf = await pngBuffer(checker);
      const flat = await service.analyseBuffer('u', flatBuf);
      const contrasty = await service.analyseBuffer('u', checkerBuf);
      expect(contrasty.contrast!).toBeGreaterThan(flat.contrast!);
    });
  });

  describe('analyseBuffer — sharpness (blur detection)', () => {
    it('scores a detailed image sharper than the same image blurred', async () => {
      // Real detail, not a flat rect — a checkerboard has actual edges for
      // the Laplacian to respond to.
      const detailed = `<svg width="600" height="600" xmlns="http://www.w3.org/2000/svg">
        ${Array.from({ length: 12 })
          .map((_, row) =>
            Array.from({ length: 12 })
              .map(
                (__, col) =>
                  `<rect x="${col * 50}" y="${row * 50}" width="50" height="50" fill="${(row + col) % 2 ? '#111' : '#eee'}"/>`,
              )
              .join(''),
          )
          .join('')}
      </svg>`;
      const sharpBuf = await pngBuffer(detailed);
      // Strong enough that the checkerboard's edges are genuinely destroyed,
      // not just softened — measureSharpness saturates its 0-1 scale fairly
      // easily, so a mild blur can still read as "1" on both sides.
      const blurredBuf = await sharp(sharpBuf).blur(40).png().toBuffer();

      const sharpProbe = await service.analyseBuffer('u', sharpBuf);
      const blurredProbe = await service.analyseBuffer('u', blurredBuf);

      expect(sharpProbe.sharpness!).toBeGreaterThan(blurredProbe.sharpness!);
    });

    it('keeps sharpness within 0–1', async () => {
      const buffer = await pngBuffer(RECT(400, 400, '#556677'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.sharpness).toBeGreaterThanOrEqual(0);
      expect(probe.sharpness).toBeLessThanOrEqual(1);
    });
  });

  describe('analyseBuffer — watermark field', () => {
    // The load-bearing decision from this phase: there is no reliable
    // automatic detector, so the field must always be null, never a
    // confident-looking number that isn't backed by anything real.
    it('always reports watermarkConfidence as null — detection is not implemented', async () => {
      const buffer = await pngBuffer(RECT(1200, 800, '#334455'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.watermarkConfidence).toBeNull();
    });
  });

  describe('analyseBuffer — dominant colour', () => {
    it('reports a hex colour close to a solid fill', async () => {
      const buffer = await pngBuffer(RECT(200, 200, '#3355ff'));
      const probe = await service.analyseBuffer('u', buffer);
      expect(probe.dominantColor).toMatch(/^#[0-9a-f]{6}$/);
    });
  });

  describe('analyseBuffer — failure handling', () => {
    it('reports ok:false for bytes that are not an image, instead of throwing', async () => {
      const probe = await service.analyseBuffer(
        'u',
        Buffer.from('not an image'),
      );
      expect(probe.ok).toBe(false);
      expect(probe.error).toBeTruthy();
    });

    it('reports ok:false for an empty buffer', async () => {
      const probe = await service.analyseBuffer('u', Buffer.alloc(0));
      expect(probe.ok).toBe(false);
    });
  });

  describe('probe — network layer', () => {
    it('fetches, then analyses the bytes', async () => {
      const buffer = await pngBuffer(RECT(500, 500, '#123456'));
      (global.fetch as jest.Mock).mockResolvedValue({
        ok: true,
        arrayBuffer: () =>
          buffer.buffer.slice(
            buffer.byteOffset,
            buffer.byteOffset + buffer.byteLength,
          ),
      });
      const probe = await service.probe(
        'https://merchant.example.com/photo.jpg',
      );
      expect(probe.ok).toBe(true);
      expect(probe.width).toBe(500);
    });

    it('reports the HTTP status on a failed fetch rather than throwing', async () => {
      (global.fetch as jest.Mock).mockResolvedValue({ ok: false, status: 404 });
      const probe = await service.probe(
        'https://merchant.example.com/missing.jpg',
      );
      expect(probe.ok).toBe(false);
      expect(probe.error).toContain('404');
    });

    it('reports a network error rather than throwing', async () => {
      (global.fetch as jest.Mock).mockRejectedValue(new Error('ECONNREFUSED'));
      const probe = await service.probe(
        'https://unreachable.example.com/x.jpg',
      );
      expect(probe.ok).toBe(false);
      expect(probe.error).toContain('ECONNREFUSED');
    });

    it('rejects a response over the size cap without buffering the whole body first', async () => {
      const huge = Buffer.alloc(13 * 1024 * 1024);
      (global.fetch as jest.Mock).mockResolvedValue({
        ok: true,
        arrayBuffer: () => huge.buffer,
      });
      const probe = await service.probe('https://x/huge.jpg');
      expect(probe.ok).toBe(false);
      expect(probe.error).toMatch(/large/i);
    });
  });

  describe('probeAll', () => {
    it('probes every url concurrently and never rejects, even if one fails', async () => {
      (global.fetch as jest.Mock).mockImplementation((url: string) =>
        url.includes('bad')
          ? Promise.reject(new Error('boom'))
          : Promise.resolve({
              ok: true,
              arrayBuffer: async () => {
                const b = await pngBuffer(RECT(300, 300, '#abcdef'));
                return b.buffer.slice(
                  b.byteOffset,
                  b.byteOffset + b.byteLength,
                );
              },
            }),
      );
      const probes = await service.probeAll([
        'https://x/good1.jpg',
        'https://x/bad.jpg',
        'https://x/good2.jpg',
      ]);
      expect(probes).toHaveLength(3);
      expect(probes.filter((p) => p.ok)).toHaveLength(2);
    });

    it('de-duplicates repeated urls', async () => {
      (global.fetch as jest.Mock).mockResolvedValue({
        ok: true,
        arrayBuffer: async () => {
          const b = await pngBuffer(RECT(300, 300, '#abcdef'));
          return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
        },
      });
      const probes = await service.probeAll([
        'https://x/a.jpg',
        'https://x/a.jpg',
      ]);
      expect(probes).toHaveLength(1);
      expect(global.fetch).toHaveBeenCalledTimes(1);
    });

    it('filters out empty/falsy urls', async () => {
      const probes = await service.probeAll([
        '',
        null as unknown as string,
        undefined as unknown as string,
      ]);
      expect(probes).toHaveLength(0);
      expect(global.fetch).not.toHaveBeenCalled();
    });
  });

  describe('toCandidates', () => {
    it('drops failed probes and maps roles via the supplied resolver', async () => {
      const buffer = await pngBuffer(RECT(1600, 1600, '#334455'));
      const probes = [
        await service.analyseBuffer('https://x/ok.jpg', buffer),
        { url: 'https://x/bad.jpg', ok: false as const, error: 'boom' },
      ];
      const candidates = service.toCandidates(probes, () => 'PRODUCT');
      expect(candidates).toHaveLength(1);
      expect(candidates[0].role).toBe('PRODUCT');
      expect(candidates[0].url).toBe('https://x/ok.jpg');
    });

    it('carries brightness/contrast/focus through to the candidate shape the ranker expects', async () => {
      const buffer = await pngBuffer(RECT(1600, 1600, '#334455'));
      const probe = await service.analyseBuffer('https://x/ok.jpg', buffer);
      const [candidate] = service.toCandidates([probe], () => 'INTERIOR');
      expect(candidate.width).toBe(1600);
      expect(candidate.brightness).toBe(probe.brightness);
      expect(candidate.focus).toBe(probe.sharpness);
    });

    // watermarkConfidence is always null today, so watermarkSuspected must
    // come out null too — "not assessed", never a false "confirmed clean".
    it('maps a null watermarkConfidence to a null watermarkSuspected, not false', async () => {
      const buffer = await pngBuffer(RECT(1600, 1600, '#334455'));
      const probe = await service.analyseBuffer('https://x/ok.jpg', buffer);
      const [candidate] = service.toCandidates([probe], () => 'PRODUCT');
      expect(candidate.watermarkSuspected).toBeNull();
    });
  });
});
