import { OfferType } from '@prisma/client';

/**
 * Module 14 Phase 3B — the Pairley marketing copy catalog.
 *
 * This is the copy that explains *how Pairley works* for a given offer type.
 * It is deliberately NOT generated by a model. Every string here is a pure
 * function of `offer_type` and `required_people` — nothing about the specific
 * merchant, dish, or price — which is exactly why it can be a fixed catalog:
 *
 *  - **Zero hallucination.** The rule "never promise that a group will form"
 *    holds because no code path can emit a promise, not because a prompt
 *    asked a model to behave and we hoped it complied on every generation.
 *  - **Zero token cost** on the path that renders a banner.
 *  - **One review.** Approve the BOGO wording once; every BOGO offer on
 *    Pairley says exactly that, forever.
 *  - **Localizable.** Entries are strings with `{{placeholders}}`, not
 *    functions, so a translator can work from a plain string table. Adding
 *    Tamil/Kannada/Telugu/Hindi is a new key in CATALOG, no code change.
 *
 * What a model *may* rewrite is the merchant's own title/description/summary
 * into house style — that lives elsewhere and is always admin-reviewed.
 * Nothing in this file is ever model output.
 *
 * ---
 * WORDING RULE, load-bearing: copy must describe the *condition*
 * ("once the required number of customers show interest…"), never the
 * *outcome* ("we'll find you a partner", "your group will fill"). Pairley
 * cannot promise that a group forms. Any new entry must follow this.
 */

export type Locale = 'en';

export const DEFAULT_LOCALE: Locale = 'en';

export interface CopyStrings {
  /** Short line for the banner. */
  headline: string;
  /** The Pairley explanation shown under the offer. */
  body: string;
  /** Used instead when the offer needs no group (required_people <= 1). */
  soloHeadline?: string;
  soloBody?: string;
}

export interface CopyContext {
  requiredPeople?: number | null;
  locale?: Locale;
}

export interface RenderedCopy {
  headline: string;
  body: string;
  /** Which catalog entry produced this — persisted on the offer so wording
   *  fixes apply retroactively without rewriting stored copy. */
  templateKey: string;
  groupRequired: boolean;
}

// Every OfferType has an entry. A missing one would silently fall back and
// show a customer nothing about how the offer works, so the type below is a
// total Record — adding a value to the enum breaks the build until its copy
// is written, which is the intended pressure.
const EN: Record<OfferType, CopyStrings> = {
  BOGO: {
    headline: 'Looking for just one seat?',
    body: 'Show interest for one seat. When another customer also shows interest, both of you unlock the Buy One Get One offer together. This reduces your per-person cost while you enjoy the same experience.',
  },
  BOGT: {
    headline: "Your group doesn't have to be complete",
    body: 'Show your interest even if your group is not complete yet. Pairley helps bring interested customers together, and once the required participation of {{people}} customers is reached, everyone benefits from the promotional pricing.',
  },
  BUY_X_GET_Y: {
    headline: 'Planning a larger outing?',
    body: 'Pairley makes it easier by bringing interested customers together. Once the required group size of {{people}} people is reached, everyone unlocks the promotional offer.',
  },
  GROUP_DISCOUNT: {
    headline: 'Better together',
    body: 'This price applies once {{people}} customers have shown interest. Add your interest now — the discount becomes available to everyone as soon as the required participation is reached.',
  },
  BULK_PURCHASE: {
    headline: 'Buy more, pay less per unit',
    body: 'Bulk pricing applies once {{people}} customers have shown interest. You do not need to buy the full quantity alone — show interest and the per-unit price drops for everyone once the requirement is met.',
    soloHeadline: 'Bulk pricing on this pack',
    soloBody:
      'This pack is priced for bulk purchase. Show interest to reserve it and see the full details.',
  },
  MEMBERSHIP_CAMPAIGN: {
    headline: 'Join alongside other members',
    body: 'Membership offers are often priced for groups. Show your interest, and once {{people}} members have joined the same offer, the promotional membership rate becomes available to everyone.',
    soloHeadline: 'Membership offer',
    soloBody:
      'Show interest to reserve this membership rate and receive the joining details.',
  },
  PACKAGE_DEAL: {
    headline: 'A package built for a group',
    body: 'This package is priced for {{people}} people. Show your interest even if your group is not complete — the package price becomes available once the required participation is reached.',
    soloHeadline: 'A complete package',
    soloBody:
      'Everything in this package at one price. Show interest to reserve it and receive the details.',
  },
  COMBO: {
    headline: 'A combo worth sharing',
    body: 'This combo is priced for {{people}} people. Show your interest and the combo price becomes available to everyone once the required participation is reached.',
    soloHeadline: 'Combo price',
    soloBody:
      'Items bundled at a single combo price. Show interest to reserve it.',
  },
  FLAT_DISCOUNT: {
    headline: 'A flat saving on this offer',
    body: 'This flat discount applies once {{people}} customers have shown interest. Add yours now and the saving becomes available to everyone as soon as the requirement is met.',
    soloHeadline: 'A flat saving on this offer',
    soloBody:
      'A fixed amount off the usual price. Show interest to reserve this offer and get the merchant details.',
  },
  PERCENTAGE_DISCOUNT: {
    headline: 'Percentage off, together',
    body: 'This percentage discount applies once {{people}} customers have shown interest. Show yours now — the discount unlocks for everyone once the required participation is reached.',
    soloHeadline: 'Percentage off',
    soloBody:
      'A percentage off the usual price. Show interest to reserve this offer and get the merchant details.',
  },
  CASHBACK: {
    headline: 'Cashback on this offer',
    body: 'Cashback applies once {{people}} customers have shown interest in this offer. Show yours to be included when the requirement is reached.',
    soloHeadline: 'Cashback on this offer',
    soloBody:
      'Earn cashback on this purchase. Show interest to reserve it and see the conditions.',
  },
  FESTIVAL: {
    headline: 'A festival offer worth sharing',
    body: 'Festival pricing applies once {{people}} customers have shown interest. Show yours now so everyone can benefit when the required participation is reached.',
    soloHeadline: 'A festival offer',
    soloBody:
      'Seasonal festival pricing for a limited period. Show interest to reserve it before it ends.',
  },
  SEASONAL: {
    headline: 'Seasonal pricing',
    body: 'This seasonal price applies once {{people}} customers have shown interest. Add yours now — it becomes available to everyone when the requirement is met.',
    soloHeadline: 'Seasonal pricing',
    soloBody:
      'Available for this season only. Show interest to reserve it before the period ends.',
  },
  FLASH_DEAL: {
    headline: 'A short-window offer',
    body: 'This flash offer runs for a limited window and applies once {{people}} customers have shown interest. Show yours early so the requirement can be reached in time.',
    soloHeadline: 'A short-window offer',
    soloBody:
      'Available for a short window only. Show interest now to reserve it.',
  },
  LIMITED_QUANTITY: {
    headline: 'Limited quantity available',
    body: 'Only a limited quantity is available at this price, and it applies once {{people}} customers have shown interest. Show yours early so the requirement can be reached while stock lasts.',
    soloHeadline: 'Limited quantity available',
    soloBody:
      'Only a limited quantity is available at this price. Show interest to reserve yours while stock lasts.',
  },
  LIMITED_TIME: {
    headline: 'Available for a limited period',
    body: 'This price is available for a limited period and applies once {{people}} customers have shown interest. Show yours early so the requirement can be reached before the period ends.',
    soloHeadline: 'Available for a limited period',
    soloBody:
      'This price is available for a limited period only. Show interest to reserve it before it ends.',
  },
  STANDARD: {
    headline: 'Show interest to reserve this offer',
    body: 'Show your interest and this offer is held for you. Once {{people}} customers have shown interest, the promotional pricing becomes available to everyone.',
    soloHeadline: 'Show interest to reserve this offer',
    soloBody:
      'Show your interest and the merchant is notified. You can then coordinate the details directly through Pairley.',
  },
};

const CATALOG: Record<Locale, Record<OfferType, CopyStrings>> = {
  en: EN,
};

/**
 * `{{people}}` interpolates to the *number only* — each template supplies
 * its own noun ("{{people}} customers", "{{people}} members"), because the
 * right noun differs per offer type and, more importantly, differs per
 * language once this catalog is translated. A placeholder that expanded to
 * "12 people" would produce "12 people customers" wherever a template
 * already had a noun.
 */
function interpolate(template: string, people: number): string {
  return template.replace(/\{\{people\}\}/g, String(people));
}

/**
 * The one entry point. Given an offer type and how many participants it
 * needs, returns the approved Pairley explanation.
 *
 * An unknown offer type falls back to STANDARD rather than throwing —
 * copy is presentation, and a customer seeing generic-but-accurate wording
 * is far better than an offer page that fails to render.
 */
export function renderPairleyCopy(
  offerType: string,
  context: CopyContext = {},
): RenderedCopy {
  const locale = context.locale ?? DEFAULT_LOCALE;
  const table = CATALOG[locale] ?? CATALOG[DEFAULT_LOCALE];

  const key =
    (offerType as OfferType) in table
      ? (offerType as OfferType)
      : OfferType.STANDARD;
  const entry = table[key];

  const requiredPeople = Number(context.requiredPeople ?? 0);
  const groupRequired = Number.isFinite(requiredPeople) && requiredPeople > 1;

  if (!groupRequired && entry.soloBody) {
    return {
      headline: entry.soloHeadline ?? entry.headline,
      body: entry.soloBody,
      templateKey: `${key}_SOLO`,
      groupRequired: false,
    };
  }

  // Group wording with no real group size would read "once 0 people…".
  const people = groupRequired ? requiredPeople : 2;

  return {
    headline: entry.headline,
    body: interpolate(entry.body, people),
    templateKey: key,
    groupRequired,
  };
}

/** Every locale/offer-type pair, for review and translation workflows. */
export function getCopyCatalog(locale: Locale = DEFAULT_LOCALE) {
  const table = CATALOG[locale] ?? CATALOG[DEFAULT_LOCALE];
  return Object.entries(table).map(([offerType, strings]) => ({
    offerType,
    ...strings,
  }));
}

export function getSupportedLocales(): Locale[] {
  return Object.keys(CATALOG) as Locale[];
}
